name: Run Flask App Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: rootpass
          MYSQL_DATABASE: teachers_connect
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    env:
      MYSQL_HOST: 127.0.0.1
      MYSQL_USER: root
      MYSQL_PASSWORD: rootpass
      MYSQL_DB: teachers_connect
      CLOUDINARY_URL: cloudinary://fake_key:fake_secret@fake_cloud

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Wait for MySQL
      run: |
        for i in {1..30}; do
          mysqladmin ping -h 127.0.0.1 -uroot -prootpass && break
          echo "Waiting for MySQL..."
          sleep 2
        done

    - name: Create test schema
      run: |
        mysql -h 127.0.0.1 -uroot -prootpass teachers_connect < schema.sql

    - name: Run tests
      run: |
        source venv/bin/activate
        pytest
